version: '3.3'
services:

  frontend:
    container_name: foodgram-front
    image: srezal/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  db:
    image: postgres:16.2-alpine
    container_name: foodgram-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    container_name: foodgram-backend
    image: srezal/foodgram-backend:latest
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - staticfiles:/app/static_backend/
      - mediafiles:/app/media_backend/
    depends_on:
      - db
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - staticfiles:/static_backend/
      - mediafiles:/media_backend/
    depends_on:
      - backend

volumes:
  staticfiles:
  mediafiles:
  pgdata:
