# Generated by Django 5.2 on 2025-05-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_favouriterecipe_favoriterecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'default_related_name': 'favorites'},
        ),
        migrations.AlterModelOptions(
            name='shoopingcart',
            options={'default_related_name': 'shopping_cart'},
        ),
    ]
