# Generated by Django 5.2 on 2025-05-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPair',
            fields=[
                ('original_link', models.CharField()),
                ('short_link', models.CharField()),
                ('pk', models.CompositePrimaryKey('original_link', 'short_link', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
