# Generated by Django 5.2 on 2025-05-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkpair',
            name='pk',
        ),
        migrations.AlterField(
            model_name='linkpair',
            name='original_link',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
