# Generated by Django 5.2 on 2025-05-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_links', '0002_remove_linkpair_pk_alter_linkpair_original_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkpair',
            options={'verbose_name': 'Пара ссылок', 'verbose_name_plural': 'Пары ссылок'},
        ),
        migrations.AlterField(
            model_name='linkpair',
            name='original_link',
            field=models.CharField(primary_key=True, serialize=False, verbose_name='Оригинальная ссылка'),
        ),
        migrations.AlterField(
            model_name='linkpair',
            name='short_link',
            field=models.CharField(verbose_name='Прямая ссылка'),
        ),
    ]
